before:
  hooks:
    - go mod tidy
builds:
  -
    id: ov-linux
    binary: ov
    ldflags:
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
  -
    id: ov-other
    binary: ov
    ldflags:
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - freebsd
    goarch:
      - '386'
      - amd64
      - arm
      - arm64

archives:
  -
    id: ov-archives
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
    - ov-linux
    - ov-other
    format: zip

nfpms:
  -
    id: ov-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
    - ov-linux
    homepage: https://github.com/hupfdule/ov
    maintainer: Nobody <nobody@nowhere.com>
    description: ov is a feature rich terminal pager.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1

    #brews:
    #  -
    #    name: ov
    #    tap:
    #      owner: hupfdule
    #      name: homebrew-tap
    #    commit_author:
    #      name: hupfdule
    #      email: nobody@nowhere.com
    #    homepage: https://github.com/hupfdule/ov
    #    description: ov is a feature rich terminal pager.
    #    install:
    #      bin.install 'ov'
